name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  merge-successful:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Merge successful pull request
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "$GIT_TOKEN" | gh auth login --with-token
          gh pr merge "$GIT_BRANCH" --rebase
