name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  check-if-should-automerge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_AUTHOR_EMAIL: ${{ github.event.workflow_run.head_commit.author.email }}
    steps:
      - name: Check if author is Helot
        run: [ "$PULL_REQUEST_AUTHOR_EMAIL" = "$GIT_EMAIL" ]

  merge-successful:
    needs: check-if-should-automerge
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_BRANCH: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Merge successful pull request
        run: |
          echo "$GIT_TOKEN" | gh auth login --with-token
          gh pr merge "$PULL_REQUEST_BRANCH" --rebase
