name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  HELOT_GIT_EMAIL: ${{ secrets.HELOT_GIT_EMAIL }}

jobs:
  merge-successful:
    if: |
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Merge successful Helot pull request
        if: github.event.workflow_run.head_commit.author.email == env.HELOT_GIT_EMAIL
        env:
          PULL_REQUEST_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          echo "$HELOT_GITHUB_ACCESS_TOKEN" | gh auth login --with-token
          gh pr merge "$PULL_REQUEST_BRANCH" --rebase
