name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      env:
        GIT_BRANCH: ${{ github.head_ref }}
    steps:
      - name: Clone (from package index)
        run: |
          brew tap logisparte/packages
          brew update
          cd "$(brew --prefix)/Homebrew/Library/Taps/logisparte/homebrew-packages"
          git checkout "$GIT_BRANCH"

      - name: Verify 'shell-helpers'
        run: |
          brew cat shell-helpers
          brew install shell-helpers
          brew audit shell-helpers
          brew test shell-helpers
          brew uninstall shell-helpers

      - name: Verify 'kano'
        run: |
          brew cat kano
          brew install kano
          brew audit kano
          brew test kano
          brew uninstall kano
