name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: true
    steps:
      - name: Retrieve package index
        run: |
          brew tap logisparte/packages
          brew update

      - name: Check all package definitions
        run: |
          cd "$(brew --prefix)/Library/Taps/logisparte/homebrew-packages" || exit 1
          git checkout "$GITHUB_HEAD_REF"
          brew developer on
          for FILE in $(ls | grep .rb); do
            FORMULA="$(echo "$FILE" | cut -d "." -f 1)"
            brew cat "$FORMULA"
            brew install "$FORMULA"
            brew audit "$FORMULA"
            brew test "$FORMULA"
            brew uninstall "$FORMULA"
          done
