name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  check_branch:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: true
      HOMEBREW_DIRECTORY: /usr/local/Homebrew
    steps:
      - name: Retrieve package index
        run: |
          brew tap logisparte/packages
          brew update

      - name: Check all package definitions
        run: |
          cd "$HOMEBREW_DIRECTORY/Library/Taps/logisparte/homebrew-packages" || exit 1
          git checkout "$GITHUB_HEAD_REF"
          brew developer on
          for FILE in $(ls | grep .rb); do
            FORMULA="$(echo "$FILE" | cut -d "." -f 1)"
            brew cat "$FORMULA"
            brew install "$FORMULA"
            brew audit "$FORMULA"
            brew test "$FORMULA"
            brew uninstall "$FORMULA"
          done
