name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/logisparte/docker-images/helot:0.1.0
    steps:
    - uses: actions/checkout@v2
    - name: Get package definitions
      run: |
        TAP_FOLDER="/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/logisparte/homebrew-packages"
        brew tap logisparte/packages
        cp "$GITHUB_WORKSPACE"/*.rb "$TAP_FOLDER"
    - name: Install packages
      run: |
        brew install shell-helpers
    - name: Audit packages
      run: |
        brew audit shell-helpers
    - name: Test packages
      run: |
        brew test shell-helpers
