name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      env:
        GIT_BRANCH: ${{ github.head_ref }}
    steps:
      - name: Clone (from package index)
        run: |
          brew tap logisparte/packages
          brew update
          cd "$(brew --prefix)/Homebrew/Library/Taps/logisparte/homebrew-packages"
          git checkout "$GIT_BRANCH"

      - name: Verify all formulas
        run: |
          for FORMULA_PATH in *.rb; do
            FORMULA="$(basename "$FORMULA_PATH" | cut -d "." -f 1)"
            brew cat "$FORMULA"
            brew install "$FORMULA"
            brew audit "$FORMULA"
            brew test "$FORMULA"
            brew uninstall "$FORMULA"
          done
