name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: homebrew/brew
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          for PACKAGE_DEFINITION in "$GITHUB_WORKSPACE"/*.rb; do
            brew install --formula "$PACKAGE_DEFINITION"
          done

      - name: Audit packages
        run: |
          for PACKAGE_DEFINITION in "$GITHUB_WORKSPACE"/*.rb; do
            PACKAGE_NAME=$(basename "$PACKAGE_DEFINITION" .rb)
            brew audit "$PACKAGE_NAME"
          done

      - name: Test packages
        run: |
          for PACKAGE_DEFINITION in "$GITHUB_WORKSPACE"/*.rb; do
            PACKAGE_NAME=$(basename "$PACKAGE_DEFINITION" .rb)
            brew test "$PACKAGE_NAME"
          done
