name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      env:
        TAP_DIRECTORY: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/logisparte/homebrew-packages
    steps:
      - name: Clone (from package index)
        env:
          GIT_BRANCH: ${{ github.head_ref }}
        run: |
          brew tap logisparte/packages
          brew update
          cd "$TAP_DIRECTORY" || exit 1
          git checkout "$GIT_BRANCH"

      - name: Verify all formulas
        run: |
          cd "$TAP_DIRECTORY" || exit 1
          for FORMULA_PATH in *.rb; do
            FORMULA="$(basename "$FORMULA_PATH" | cut -d "." -f 1)"
            brew cat "$FORMULA"
            brew install "$FORMULA"
            brew audit "$FORMULA"
            brew test "$FORMULA"
            brew uninstall "$FORMULA"
          done
